spring:
  application:
    name: knowledge-base
  # 数据库配置
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST_PORT}/${DATABASE_DB:kxj}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  # JPA 配置
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:redis}
      password: ${REDIS_PASSWORD}

# Ollama 配置
langchain4j:
  ollama:
    base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
    chat-model:
      model-name: qwen2:7b
      temperature: 0.7
      timeout: ${OLLAMA_CHAT_TIMEOUT:1h}
    embedding-model:
      model-name: nomic-embed-text
      timeout: ${OLLAMA_EMBEDDING_TIMEOUT:1h}
